resource "helm_release" "argo_workflows" {
	chart="argo-workflows"
	depends_on=[
		kubernetes_namespace.argocd,
	]
	name="argo-workflows"
	namespace=var.argo_workflows_namespace
	repository="https://argoproj.github.io/argo-helm"
	upgrade_install=true
	values=[
		yamlencode(
			{
				controller={
					podSecurityContext={
						runAsNonRoot=true
						runAsUser=1000
						seccompProfile={
							type="RuntimeDefault"
						}
					}
					resources={
						limits={
							memory="512Mi"
						}
						requests={
							cpu="15m"
							memory="128Mi"
						}
					}
					securityContext={
						allowPrivilegeEscalation=false
						capabilities={
							drop=["ALL"]
						}
						readOnlyRootFilesystem=true
					}
				}
				server={
					podSecurityContext={
						runAsNonRoot=true
						runAsUser=1000
						seccompProfile={
							type="RuntimeDefault"
						}
					}
					resources={
						limits={
							memory="256Mi"
						}
						requests={
							cpu="15m"
							memory="128Mi"
						}
					}
					securityContext={
						allowPrivilegeEscalation=false
						capabilities={
							drop=["ALL"]
						}
						readOnlyRootFilesystem=true
					}
				}
			}),
	]
	version="0.47.3"
}
resource "kubernetes_namespace" "argo_workflows" {
	metadata {
		labels=merge(
			local.common_labels,
			{
				"pod-security.kubernetes.io/enforce"="restricted"
			}
		)
		name=var.argo_workflows_namespace
	}
}