resource "helm_release" "crossplane" {
	atomic=true
	chart="crossplane"
	cleanup_on_fail=true
	create_namespace=false
	name="crossplane"
	namespace=var.crossplane_namespace
	repository="https://charts.crossplane.io/stable"
	values=[
		yamlencode(
			{
				podSecurityContextCrossplane=local.default_crossplane_pod_security_context
				podSecurityContextRBACManager=local.default_crossplane_pod_security_context
				securityContextCrossplane=local.default_crossplane_container_security_context
				securityContextRBACManager=local.default_crossplane_container_security_context
				resourcesCrossplane={
					limits={
						memory="2Gi"
					}
					requests={
						cpu="63m"
						memory="768Mi"
					}
				}
				resourcesRBACManager={
					limits={
						memory="512Mi"
					}
					requests={
						cpu="15m"
						memory="256Mi"
					}
				}
			})
	]
	version="2.1.3"
	wait=true
}

resource "kubernetes_namespace" "crossplane" {
	metadata {
		name=var.crossplane_namespace
		labels=merge(
			local.common_labels,
			{
				"pod-security.kubernetes.io/enforce"="restricted"
			}
		)
	}
}